# Configuration file of FAR training experiment

# ========== Cluster configuration ========== 
# ip address of the parameter server (need 1 GPU process)

ps_ip: 128.232.115.65  # tarawera
# ps_ip: 128.232.115.66 # ngongotaha
# ps_ip: 128.232.115.0  # mauao
# ps_ip: 127.0.0.1

# ip address of each worker:# of available gpus process on each gpu in this node
# Note that if we collocate ps and worker on same GPU, then we need to decrease this number of available processes on that GPU by 1
# E.g., master node has 4 available processes, then 1 for the ps, and worker should be set to: worker:3
worker_ips: 
    - 128.232.115.65:[4] # worker_ip: [(# processes on gpu) for gpu in available_gpus] eg. 10.0.0.2:[4,4,4,4] This node has 4 gpus, each gpu has 4 processes.
    - 128.232.115.66:[4]
    #- 128.232.115.0:[1]

cuda_ids: [[0],[0]]

exp_path: /nfs-share/yan/FedScale/new_FedScale/core

# Entry function of executor and aggregator under $exp_path
executor_entry: executor.py

aggregator_entry: aggregator.py

auth:
    ssh_user: "yan"
    ssh_private_key: ~/.ssh/id_rsa

# cmd to run before we can indeed run FAR (in order)
setup_commands:
    - . /nfs-share/yan/miniconda3/bin/activate fedscale
    - export NCCL_SOCKET_IFNAME='enp1s0f0'         # Run "ifconfig" to ensure the right NIC for nccl if you have multiple NICs

# ========== Additional job configuration ========== 
# Default parameters are specified in argParser.py, wherein more description of the parameter can be found

job_conf: 
    - job_name: femnist                   # Generate logs under this folder: log_path/job_name/time_stamp
    - log_path: /nfs-share/yan/FedScale/new_FedScale/core/evals # Path of log files
    - total_worker: 3                      # Number of participants per round, we use K=100 in our paper, large K will be much slower
    - data_set: femnist                     # Dataset: openImg, google_speech, stackoverflow
    - data_dir: /datasets/FedScale/leaf_femnist    # Path of the dataset
    - data_map_file: /datasets/FedScale/leaf_femnist/client_data_mapping/train.csv              # Allocation of data to each client, turn to iid setting if not provided
    - device_conf_file: /nfs-share/yan/FedScale/new_FedScale/dataset/data/device_info/client_device_capacity     # Path of the client trace
    - device_avail_file: /nfs-share/yan/FedScale/new_FedScale/dataset/data/device_info/client_behave_trace
    - model: femnist                            # Models: e.g., shufflenet_v2_x2_0, mobilenet_v2, resnet34, albert-base-v2
    - gradient_policy: avg                 # {"fed-yogi", "fed-prox", "fed-avg"}, "fed-avg" by default
    - eval_interval: 5                     # How many rounds to run a testing on the testing set
    - epochs: 2000                          # Number of rounds to run this training. We use 1000 in our paper, while it may converge w/ ~400 rounds
    - filter_less: 1                       # Remove clients w/ less than 21 samples
    - num_loaders: 2
    #- yogi_eta: 3e-3
    #- yogi_tau: 1e-8
    - local_steps: 80
    - local_epochs: 1
    - learning_rate: 0.004
    - batch_size: 10
    - test_bsz: 10
    - malicious_factor: 4
    - task: femnist


